"""empty message

Revision ID: 3be8970ff77d
Revises: 831693c222fc
Create Date: 2019-04-04 17:13:53.104489

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3be8970ff77d'
down_revision = '831693c222fc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chain',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('hotels_owned', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=128), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('address', sa.Integer(), nullable=True),
    sa.Column('phone', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['address'], ['addr.id'], ),
    sa.ForeignKeyConstraint(['phone'], ['phone.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('hotel',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rooms_amt', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=128), nullable=False),
    sa.Column('address', sa.Integer(), nullable=True),
    sa.Column('phone', sa.Integer(), nullable=True),
    sa.Column('manager', sa.Integer(), nullable=True),
    sa.Column('owned_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['address'], ['addr.id'], ),
    sa.ForeignKeyConstraint(['manager'], ['employee.id'], ),
    sa.ForeignKeyConstraint(['owned_by'], ['chain.id'], ),
    sa.ForeignKeyConstraint(['phone'], ['phone.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('room',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('price', sa.Numeric(), nullable=False),
    sa.Column('condition', sa.String(length=256), nullable=False),
    sa.Column('view', sa.String(length=256), nullable=False),
    sa.Column('amenities', sa.String(length=256), nullable=False),
    sa.Column('extendable', sa.Boolean(), nullable=False),
    sa.Column('hotel', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['hotel'], ['hotel.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('booking',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('checked_in', sa.Boolean(), nullable=False),
    sa.Column('from_date', sa.Date(), nullable=True),
    sa.Column('to_date', sa.Date(), nullable=True),
    sa.Column('room', sa.Integer(), nullable=True),
    sa.Column('customer', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['customer'], ['customer.id'], ),
    sa.ForeignKeyConstraint(['room'], ['room.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('from_date'),
    sa.UniqueConstraint('to_date')
    )
    op.create_table('archive',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('booking', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['booking'], ['booking.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('archive')
    op.drop_table('booking')
    op.drop_table('room')
    op.drop_table('hotel')
    op.drop_table('chain')
    # ### end Alembic commands ###
