"""empty message

Revision ID: a76812acc0b0
Revises: 3be8970ff77d
Create Date: 2019-04-04 18:05:07.356152

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a76812acc0b0'
down_revision = '3be8970ff77d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('archive', sa.Column('booking_id', sa.Integer(), nullable=True))
    op.drop_constraint(None, 'archive', type_='foreignkey')
    op.create_foreign_key(None, 'archive', 'booking', ['booking_id'], ['id'])
    op.drop_column('archive', 'booking')
    op.drop_constraint(None, 'booking', type_='foreignkey')
    op.create_foreign_key(None, 'booking', 'user', ['customer'], ['id'])
    op.add_column('room', sa.Column('hotel_id', sa.Integer(), nullable=True))
    op.add_column('room', sa.Column('image_url', sa.String(length=256), nullable=False))
    op.drop_constraint(None, 'room', type_='foreignkey')
    op.create_foreign_key(None, 'room', 'hotel', ['hotel_id'], ['id'])
    op.drop_column('room', 'hotel')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('room', sa.Column('hotel', sa.INTEGER(), nullable=True))
    op.drop_constraint(None, 'room', type_='foreignkey')
    op.create_foreign_key(None, 'room', 'hotel', ['hotel'], ['id'])
    op.drop_column('room', 'image_url')
    op.drop_column('room', 'hotel_id')
    op.drop_constraint(None, 'booking', type_='foreignkey')
    op.create_foreign_key(None, 'booking', 'customer', ['customer'], ['id'])
    op.add_column('archive', sa.Column('booking', sa.INTEGER(), nullable=True))
    op.drop_constraint(None, 'archive', type_='foreignkey')
    op.create_foreign_key(None, 'archive', 'booking', ['booking'], ['id'])
    op.drop_column('archive', 'booking_id')
    # ### end Alembic commands ###
