"""empty message

Revision ID: db427c55a9be
Revises: 79420754a4a0
Create Date: 2019-04-05 10:54:05.671162

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'db427c55a9be'
down_revision = '79420754a4a0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('employee')
    op.drop_table('customer')
    op.add_column('booking', sa.Column('user', sa.Integer(), nullable=True))
    op.drop_constraint(None, 'booking', type_='foreignkey')
    op.create_foreign_key(None, 'booking', 'user', ['user'], ['id'])
    op.drop_column('booking', 'customer')
    op.drop_constraint(None, 'hotel', type_='foreignkey')
    op.create_foreign_key(None, 'hotel', 'user', ['manager'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'hotel', type_='foreignkey')
    op.create_foreign_key(None, 'hotel', 'employee', ['manager'], ['id'])
    op.add_column('booking', sa.Column('customer', sa.INTEGER(), nullable=True))
    op.drop_constraint(None, 'booking', type_='foreignkey')
    op.create_foreign_key(None, 'booking', 'customer', ['customer'], ['id'])
    op.drop_column('booking', 'user')
    op.create_table('customer',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('employee',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('position', sa.VARCHAR(length=16), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
